name: Deploy To Prod On Push Tag (aiii-api-med)

'on':
  push:
    tags:
      - 's*'

env:
  PROJECT_ID: chihhaoproject
  DEPLOYMENT_NAME: chihhao-api
  REPOSITORY: developer-docker
  IMAGE: chihhao-api
  SERVICE: chihhao-api
  CHIHHAO_NPM_DOWNLOAD_TOKEN: ${{ secrets.CHIHHAO_NPM_DOWNLOAD_TOKEN }}


jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build tools
        run: |
          sudo apt-get install -y build-essential
          npm install -g node-gyp

      - name: Get Tag Name & Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_COOLYHUANG_GITHUB_KEY }}
          export_default_credentials: true

      - name: Set Configure Docker
        run: gcloud auth configure-docker asia-east1-docker.pkg.dev

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run Build
        run: npm run build

      #      - name: Run Test
      #        run: npm run test

      - name: Docker Build Image
        run: docker build -t asia-east1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ env.RELEASE_VERSION }} -t asia-east1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:latest .

      - name: Docker Push Image
        run: docker push asia-east1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }} --all-tags

      - name: Deploy To Cloud Run
        run: 'gcloud run deploy ${{ env.SERVICE }} --image asia-east1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ env.RELEASE_VERSION }} --region asia-east1 --platform managed --allow-unauthenticated'